In [1]:
import pandas as pd

df = pd.read_csv("../Data/Preprocessed_Data/clean_data.csv")
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker,Currency
0,0.000,0.237333,0.239196,0.239838,203.114197,0.084147,0.0,0.0,0.0,0.0
1,0.004,0.239131,0.239581,0.237177,200.653961,0.134526,0.0,0.0,0.0,0.0
2,0.008,0.234227,0.237460,0.237898,201.869156,0.099623,0.0,0.0,0.0,0.0
3,0.012,0.237980,0.237653,0.235067,197.994522,0.111744,0.0,0.0,0.0,0.0
4,0.016,0.232261,0.231457,0.233691,198.412857,0.078961,0.0,0.0,0.0,0.0

In [1]:
import pandas as pd

df = pd.read_csv("../Data/Preprocessed_Data/X_test.csv")
df.head()

,Date,Open,High,Low,Volume,Dividends,Stock Splits,Ticker,Currency
0,0.640,0.542884,0.539431,0.541722,0.067119,0.0,0.0,0.909091,0.0
1,0.356,0.021434,0.021940,0.020684,0.220960,0.0,0.0,0.454545,0.0
2,0.628,0.539961,0.554893,0.544275,0.132001,0.0,0.0,0.909091,0.0
3,0.208,0.267774,0.266290,0.268649,0.053472,0.0,0.0,0.000000,0.0
4,0.560,0.841766,0.837376,0.844430,0.008404,0.0,0.0,0.545455,0.0

In [2]:
import pandas as pd

df = pd.read_csv("../Data/Preprocessed_Data/y_test.csv")
df.head()

        Close
0  430.899994
1   35.630001
2  449.359985
3  224.265518
4  662.722595

In [2]:
df.info()
df.isnull().sum()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3012 entries, 0 to 3011
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3012 non-null   float64
 1   Open          3012 non-null   float64
 2   High          3012 non-null   float64
 3   Low           3012 non-null   float64
 4   Close         3012 non-null   float64
 5   Volume        3012 non-null   float64
 6   Dividends     3012 non-null   float64
 7   Stock Splits  3012 non-null   float64
 8   Ticker        3012 non-null   float64
 9   Currency      3012 non-null   float64
dtypes: float64(10)
memory usage: 235.4 KB

(3012, 10)